version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:00"
      timezone: America/Toronto
    open-pull-requests-limit: 5
    allow:
      - dependency-name: "*"
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch
    groups:
      routine-updates:
        applies-to: version-updates
        patterns: ["*"]
        update-types: [minor, patch]
      security-updates:
        applies-to: security-updates
        patterns: ["*"]
